# Generated by Django 2.1.5 on 2019-01-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190108_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='employee',
        ),
    ]
