# Generated by Django 2.1.5 on 2019-01-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('stuff', 'Stuff'), ('admin', 'Admin')], default='stuff', max_length=20),
        ),
    ]
