# Generated by Django 2.1.5 on 2019-01-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190112_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='task',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
            preserve_default=False,
        ),
    ]
